// Mock proposals data
export const mockProposals = [
  {
    id: 1,
    title: "[CONSTITUTIONAL] AIP: ArbOS Version 50 Dia",
    forumLink: "https://forum.arbitrum.foundation/t/constitutional-aip-arbos-version-50-dia/29835",
    snapshotLink: null,
    tallyLink: null,
    forumStatus: "Active Discussion",
    snapshotStatus: null,
    tallyStatus: null,
    forumLastUpdate: "3d ago",
    snapshotLastUpdate: null,
    tallyLastUpdate: null,
    category: "Constitutional",
    author: "Offchain Labs",
    description: "Upgrade Arbitrum One and Nova to ArbOS 50 Dia with Fusaka compatibility",
  },
  {
    id: 2,
    title: "[CONSTITUTIONAL] Register $BORING in the Arbitrum generic-custom gateway",
    forumLink:
      "https://forum.arbitrum.foundation/t/constitutional-register-boring-in-the-arbitrum-generic-custom-gateway/29206",
    snapshotLink: "https://snapshot.box/#/s:arbitrumfoundation.eth/proposal/0x123",
    tallyLink:
      "https://www.tally.xyz/gov/arbitrum/proposal/97685288731263391833044854304895851471157040105038894699042975271050068874277",
    forumStatus: "Completed",
    snapshotStatus: "Passed",
    tallyStatus: "Executed",
    forumLastUpdate: "24d ago",
    snapshotLastUpdate: "18d ago",
    tallyLastUpdate: "12d ago",
    category: "Constitutional",
    author: "L2BEAT",
    description: "Register $BORING token in Arbitrum bridge for cross-chain functionality",
    votes: { for: "212.95M", against: "43.07K", total: "213.08M" },
    executionDate: "Jul 28th, 2025",
  },
  {
    id: 3,
    title: "Entropy Advisors: Exclusively Working with the Arbitrum DAO",
    forumLink:
      "https://forum.arbitrum.foundation/t/entropy-advisors-exclusively-working-with-the-arbitrum-dao-y2-y3/29458",
    snapshotLink: "https://snapshot.box/#/s:arbitrumfoundation.eth/proposal/0x456",
    tallyLink:
      "https://www.tally.xyz/gov/arbitrum/proposal/37638751032596392177176596241110468090299645534448966767963399982622616318705",
    forumStatus: "Completed",
    snapshotStatus: "Passed",
    tallyStatus: "Pending execution (Proposal queued)",
    forumLastUpdate: "45d ago",
    snapshotLastUpdate: "32d ago",
    tallyLastUpdate: "2d ago",
    category: "Treasury",
    author: "Entropy Advisors",
    description: "Exclusive engagement proposal for treasury management services",
    votes: { for: "158.68M", against: "16.59M", total: "215.95M" },
  },
  {
    id: 4,
    title: "Proposal: Revert the Delegate Incentive Program (DIP) to Version 1.5",
    forumLink:
      "https://forum.arbitrum.foundation/t/proposal-revert-the-delegate-incentive-program-dip-to-version-1-5/29867",
    snapshotLink: null,
    tallyLink: null,
    forumStatus: "Active Discussion",
    snapshotStatus: null,
    tallyStatus: null,
    forumLastUpdate: "16h ago",
    snapshotLastUpdate: null,
    tallyLastUpdate: null,
    category: "Non-Constitutional",
    author: "Instinct",
    description: "Proposal to revert DIP changes and return to previous version",
  },
  {
    id: 5,
    title: "[Constitutional] AIP: Constitutional Quorum Threshold Reduction",
    forumLink: "https://forum.arbitrum.foundation/t/constitutional-aip-constitutional-quorum-threshold-reduction/29145",
    snapshotLink: "https://snapshot.box/#/s:arbitrumfoundation.eth/proposal/0x789",
    tallyLink:
      "https://www.tally.xyz/gov/arbitrum/proposal/94423886836435773843507976898262621297544156552971145658873213763398017341229",
    forumStatus: "Completed",
    snapshotStatus: "Passed",
    tallyStatus: "Executed",
    forumLastUpdate: "21d ago",
    snapshotLastUpdate: "18d ago",
    tallyLastUpdate: "15d ago",
    category: "Constitutional",
    author: "Arbitrum Foundation",
    description: "Reduce quorum threshold to improve governance participation",
    votes: { for: "215.7M", against: "6.31M", total: "241.01M" },
    executionDate: "Jun 16th, 2025",
  },
  {
    id: 6,
    title: "[Treasury] Fund Arbitrum Gaming Catalyst Program",
    forumLink: "https://forum.arbitrum.foundation/t/fund-arbitrum-gaming-catalyst-program/29234",
    snapshotLink: "https://snapshot.box/#/s:arbitrumfoundation.eth/proposal/0xabc",
    tallyLink:
      "https://www.tally.xyz/gov/arbitrum/proposal/12345678901234567890123456789012345678901234567890123456789012345678901234567890",
    forumStatus: "Completed",
    snapshotStatus: "Passed",
    tallyStatus: "Pending execution (L2 Execution)",
    forumLastUpdate: "35d ago",
    snapshotLastUpdate: "28d ago",
    tallyLastUpdate: "5d ago",
    category: "Treasury",
    author: "Gaming DAO",
    description: "Funding proposal for gaming ecosystem development",
    votes: { for: "189.45M", against: "12.33M", total: "201.78M" },
  },
  {
    id: 7,
    title: "[Non-Constitutional] Arbitrum Research & Development Collective",
    forumLink: "https://forum.arbitrum.foundation/t/arbitrum-research-development-collective/29567",
    snapshotLink: "https://snapshot.box/#/s:arbitrumfoundation.eth/proposal/0xdef",
    tallyLink:
      "https://www.tally.xyz/gov/arbitrum/proposal/98765432109876543210987654321098765432109876543210987654321098765432109876543210",
    forumStatus: "Completed",
    snapshotStatus: "Passed",
    tallyStatus: "Pending execution (L2-to-L1 message)",
    forumLastUpdate: "42d ago",
    snapshotLastUpdate: "35d ago",
    tallyLastUpdate: "7d ago",
    category: "Non-Constitutional",
    author: "Research Collective",
    description: "Establish research and development collective for Arbitrum ecosystem",
    votes: { for: "167.89M", against: "8.91M", total: "176.80M" },
  },
  {
    id: 8,
    title: "[Constitutional] Update Arbitrum Security Council Election Process",
    forumLink: "https://forum.arbitrum.foundation/t/update-arbitrum-security-council-election-process/29678",
    snapshotLink: "https://snapshot.box/#/s:arbitrumfoundation.eth/proposal/0x999",
    tallyLink:
      "https://www.tally.xyz/gov/arbitrum/proposal/11111111111111111111111111111111111111111111111111111111111111111111111111111111",
    forumStatus: "Completed",
    snapshotStatus: "Failed",
    tallyStatus: "Canceled",
    forumLastUpdate: "28d ago",
    snapshotLastUpdate: "21d ago",
    tallyLastUpdate: "18d ago",
    category: "Constitutional",
    author: "Security Council",
    description: "Proposed updates to security council election procedures",
    votes: { for: "89.12M", against: "156.78M", total: "245.90M" },
  },
  {
    id: 9,
    title: "[Treasury] Arbitrum Developer Incentive Program Phase 2",
    forumLink: "https://forum.arbitrum.foundation/t/arbitrum-developer-incentive-program-phase-2/29789",
    snapshotLink: "https://snapshot.box/#/s:arbitrumfoundation.eth/proposal/0xdev2",
    tallyLink: null,
    forumStatus: "Completed",
    snapshotStatus: "Passed",
    tallyStatus: null,
    forumLastUpdate: "25d ago",
    snapshotLastUpdate: "8d ago",
    tallyLastUpdate: null,
    category: "Treasury",
    author: "Developer DAO",
    description: "Second phase of developer incentive program with expanded scope",
    votes: { for: "198.45M", against: "22.15M", total: "220.60M" },
  },
  {
    id: 10,
    title: "[Non-Constitutional] Arbitrum Ecosystem Growth Initiative",
    forumLink: "https://forum.arbitrum.foundation/t/arbitrum-ecosystem-growth-initiative/29823",
    snapshotLink: "https://snapshot.box/#/s:arbitrumfoundation.eth/proposal/0xgrow",
    tallyLink: null,
    forumStatus: "Completed",
    snapshotStatus: "Passed",
    tallyStatus: null,
    category: "Non-Constitutional",
    author: "Ecosystem Team",
    description: "Comprehensive initiative to accelerate ecosystem growth and adoption",
    votes: { for: "176.89M", against: "18.44M", total: "195.33M" },
  },
];

export type Proposal = (typeof mockProposals)[number];
